### ISSUE TITLE
写得很不错，你看看今年创新展的投票系统

### ISSUE THREAD

**Issue by hansnow** [dukewan/buptVote#1]
垃圾到让人无法吐槽

**Comment by dukewan** [comment]
@hansnow 嘿嘿 多谢夸奖 : ) 求个今年的链接

**Comment by hansnow** [comment]
在内网：http://10.3.240.199/index.jsp

**Comment by dukewan** [comment]
@hansnow  soga 确实不太直观啊，也很丑。。

**Comment by talhajavaidmalik** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
AppServiceProvider, @santoshjoshi, @zapragartiast, @ajesse11x, @bvishwanathr, @holgun, @AaronGoldsmith1, @dostiharise, @liwuhou, @asanmateu, @zzzhai, @mario21ic, @baharalidurrani, @namansancheti, @eliajhmauve, @rohinibarla, @tanxeel, @sean-lin-tw, @chrisnft, @ketsakda
